### ISSUE TITLE
Geeting an error while running make for mdt-dialout-collector

### ISSUE THREAD

**Issue by Kevin-Patel119** [scuzzilla/mdt-dialout-collector#13]
- I've tried this example https://grpc.io/docs/languages/cpp/quickstart/#build-the-example and it works.
- Cloned https://github.com/scuzzilla/mdt-dialout-collector.git and converted to .zip file and and unzip on my Linux machine.
-  cmake ran successfully 
[cmake.txt](https://github.com/scuzzilla/mdt-dialout-collector/files/9546731/cmake.txt)
- Getting an error while running make,
[make.txt](https://github.com/scuzzilla/mdt-dialout-collector/files/9546742/make.txt)
- Now it got failed at 3% in make,
[make1.txt](https://github.com/scuzzilla/mdt-dialout-collector/files/9546755/make1.txt)
- System configuration 
[systemconfig.txt](https://github.com/scuzzilla/mdt-dialout-collector/files/9546843/systemconfig.txt)
- @scuzzilla Let me know if you need any other information.

**Comment by Kevin-Patel119** [comment]
- cmake ran successfully
[root@localhost mdt-dialout-collector]# cd build/
[root@localhost build]# cmake ../
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.4.2") 
-- The C compiler identification is GNU 8.3.1
-- The CXX compiler identification is GNU 8.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Protobuf: /root/.local/bin/protoc-3.19.4.0 (found version "3.19.4.0") 
-- Using protobuf 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using gRPC 1.46.3
-- Checking for module 'jsoncpp>=1.8.4'
--   Found jsoncpp, version 1.8.4
-- Using jsoncpp 1.8.4
-- Checking for module 'rdkafka++>=1.6.2'
--   Found rdkafka++, version 1.9.2
-- Using librdkafka++ 1.9.2
-- Checking for module 'rdkafka>=1.6.2'
--   Found rdkafka, version 1.9.2
-- Using librdkafka 1.9.2
-- Checking for module 'libconfig++>=1.5'
--   Found libconfig++, version 1.5
-- Using libconfig++ 1.5
-- Checking for module 'spdlog>=1.5.0'
--   Found spdlog, version 1.5.0
-- Using spdlog 1.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/mdt-dialout-collector/build


- Getting an error while running make,
[root@localhost build]# make
[  3%] Generating ../src/proto/OpenConfig/openconfig_interfaces.pb.cc, ../src/proto/OpenConfig/openconfig_interfaces.pb.h
[  7%] Generating ../src/proto/Cisco/cisco_dialout.pb.cc, ../src/proto/Cisco/cisco_dialout.pb.h, ../src/proto/Cisco/cisco_dialout.grpc.pb.cc, ../src/proto/Cisco/cisco_dialout.grpc.pb.h
[ 10%] Generating ../src/proto/Cisco/cisco_telemetry.pb.cc, ../src/proto/Cisco/cisco_telemetry.pb.h
[ 14%] Generating ../src/proto/Huawei/huawei_dialout.pb.cc, ../src/proto/Huawei/huawei_dialout.pb.h, ../src/proto/Huawei/huawei_dialout.grpc.pb.cc, ../src/proto/Huawei/huawei_dialout.grpc.pb.h
[ 17%] Generating ../src/proto/Huawei/huawei_telemetry.pb.cc, ../src/proto/Huawei/huawei_telemetry.pb.h
[ 21%] Generating ../src/proto/Juniper/juniper_gnmi.pb.cc, ../src/proto/Juniper/juniper_gnmi.pb.h, ../src/proto/Juniper/juniper_gnmi.grpc.pb.cc, ../src/proto/Juniper/juniper_gnmi.grpc.pb.h, ../src/proto/Juniper/juniper_dialout.pb.cc, ../src/proto/Juniper/juniper_dialout.pb.h, ../src/proto/Juniper/juniper_dialout.grpc.pb.cc, ../src/proto/Juniper/juniper_dialout.grpc.pb.h
[ 25%] Generating ../src/proto/Juniper/juniper_gnmi_ext.pb.cc, ../src/proto/Juniper/juniper_gnmi_ext.pb.h, ../src/proto/Juniper/juniper_telemetry.pb.cc, ../src/proto/Juniper/juniper_telemetry.pb.h, ../src/proto/Juniper/juniper_telemetry_header.pb.cc, ../src/proto/Juniper/juniper_telemetry_header.pb.h, ../src/proto/Juniper/juniper_telemetry_header_extension.pb.cc, ../src/proto/Juniper/juniper_telemetry_header_extension.pb.h
[ 28%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/mdt_dialout_collector.cc.o
[ 32%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/core/mdt_dialout_core.cc.o
[ 35%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/utils/cfg_handler.cc.o
[ 39%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/utils/logs_handler.cc.o
[ 42%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/dataManipulation/data_manipulation.cc.o
[ 46%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/dataDelivery/data_delivery.cc.o
[ 50%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Cisco/cisco_dialout.pb.cc.o
[ 53%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Cisco/cisco_dialout.grpc.pb.cc.o
[ 57%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Cisco/cisco_telemetry.pb.cc.o
[ 60%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_gnmi.pb.cc.o
[ 64%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_gnmi_ext.pb.cc.o
[ 67%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_dialout.pb.cc.o
[ 71%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_dialout.grpc.pb.cc.o
[ 75%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_telemetry.pb.cc.o
[ 78%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_telemetry_header.pb.cc.o
[ 82%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_telemetry_header_extension.pb.cc.o
[ 85%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Huawei/huawei_dialout.pb.cc.o
[ 89%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Huawei/huawei_dialout.grpc.pb.cc.o
[ 92%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Huawei/huawei_telemetry.pb.cc.o
[ 96%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/OpenConfig/openconfig_interfaces.pb.cc.o
[100%] Linking CXX executable ../bin/mdt_dialout_collector
CMakeFiles/mdt_dialout_collector.dir/src/utils/cfg_handler.cc.o: In function `std::filesystem::exists(std::filesystem::__cxx11::path const&)':
cfg_handler.cc:(.text._ZNSt10filesystem6existsERKNS_7__cxx114pathE[_ZNSt10filesystem6existsERKNS_7__cxx114pathE]+0x14): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
CMakeFiles/mdt_dialout_collector.dir/src/utils/cfg_handler.cc.o: In function `std::filesystem::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::filesystem::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::filesystem::__cxx11::path::format)':
cfg_handler.cc:(.text._ZNSt10filesystem7__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC5INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE]+0x64): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/mdt_dialout_collector.dir/build.make:557: ../bin/mdt_dialout_collector] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/mdt_dialout_collector.dir/all] Error 2
make: *** [Makefile:91: all] Error 2


- Now it got failed at 3% in make,
[root@localhost build]# make LDLIBS=-lstdc++fs
[  3%] Linking CXX executable ../bin/mdt_dialout_collector
CMakeFiles/mdt_dialout_collector.dir/src/utils/cfg_handler.cc.o: In function `std::filesystem::exists(std::filesystem::__cxx11::path const&)':
cfg_handler.cc:(.text._ZNSt10filesystem6existsERKNS_7__cxx114pathE[_ZNSt10filesystem6existsERKNS_7__cxx114pathE]+0x14): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
CMakeFiles/mdt_dialout_collector.dir/src/utils/cfg_handler.cc.o: In function `std::filesystem::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::filesystem::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::filesystem::__cxx11::path::format)':
cfg_handler.cc:(.text._ZNSt10filesystem7__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC5INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE]+0x64): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/mdt_dialout_collector.dir/build.make:557: ../bin/mdt_dialout_collector] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/mdt_dialout_collector.dir/all] Error 2
make: *** [Makefile:91: all] Error 2


- System configuration
[root@localhost build]# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC) 


- [root@localhost build]# hostnamectl

   Static hostname: localhost.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 79f37f33696042be9eba5842a2f67105
           Boot ID: 92e43bb606994e33b93f11f6008e6aed
    Virtualization: vmware
  Operating System: Red Hat Enterprise Linux 8.2 (Ootpa)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:8.2:GA
            Kernel: Linux 4.18.0-193.el8.x86_64
      Architecture: x86-64
[root@localhost build]# 

- [root@localhost build]# cmake --version
cmake version 3.20.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).

- [root@localhost build]# git --version
git version 2.18.2
[root@localhost build]#

**Comment by scuzzilla** [comment]
pls, check the README. Specifically, the "additional notes" related to CentOS should be, most probably, valid for RH.

**Comment by Kevin-Patel119** [comment]
@scuzzilla I had already followed https://github.com/scuzzilla/mdt-dialout-collector#additional-install-notes

[root@localhost ~]# echo $HOME
/root
[root@localhost ~]# export MY_INSTALL_DIR=$HOME/.local
[root@localhost ~]# echo $MY_INSTALL_DIR
/root/.local
[root@localhost ~]# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
[root@localhost ~]# export PATH="$MY_INSTALL_DIR/bin:$PATH"
[root@localhost ~]# echo $PATH
/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
[root@localhost ~]# echo $PKG_CONFIG_PATH

[root@localhost ~]# ls -la /usr/local/lib
total 0
drwxr-xr-x.  2 root root   6 Aug 12  2018 .
drwxr-xr-x. 12 root root 131 Sep  7 09:18 ..
[root@localhost ~]# export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig/
[root@localhost ~]# echo $PKG_CONFIG_PATH
:/usr/local/lib/pkgconfig/
[root@localhost ~]# cat /usr/include/spdlog/tweakme.h | grep -A1 -B1 SPDLOG_FMT_EXTERNAL
//
#define SPDLOG_FMT_EXTERNAL
///////////////////////////////////////////////////////////////////////////////
[root@localhost ~]# 

[root@localhost mdt-dialout-collector]# ll
total 36
drwx------ 2 root root    23 Sep 12 09:47 bin
drwx------ 3 root root   118 Sep 12 09:47 build
-rw------- 1 root root 14194 Sep  8 12:55 CMakeLists.txt
drwx------ 2 root root    23 Sep  8 12:55 csv
-rw------- 1 root root  1096 Sep  8 12:55 LICENSE
drwx------ 6 root root    66 Sep  8 12:55 proto
drwx------ 2 root root    23 Sep  8 12:55 ptm
-rw------- 1 root root 12598 Sep  8 12:55 README.md
drwx------ 8 root root   135 Sep  8 12:55 src
[root@localhost mdt-dialout-collector]# pushd build
/opt/mdt-dialout-collector/build /opt/mdt-dialout-collector
[root@localhost build]# cmake ../
-- Using protobuf 
-- Using gRPC 1.46.3
-- Using jsoncpp 1.8.4
-- Using librdkafka++ 1.9.2
-- Using librdkafka 1.9.2
-- Using libconfig++ 1.5
-- Using spdlog 1.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/mdt-dialout-collector/build
[root@localhost build]# make
Consolidate compiler generated dependencies of target mdt_dialout_collector
[  3%] Linking CXX executable ../bin/mdt_dialout_collector
CMakeFiles/mdt_dialout_collector.dir/src/utils/cfg_handler.cc.o: In function `std::filesystem::exists(std::filesystem::__cxx11::path const&)':
cfg_handler.cc:(.text._ZNSt10filesystem6existsERKNS_7__cxx114pathE[_ZNSt10filesystem6existsERKNS_7__cxx114pathE]+0x14): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
CMakeFiles/mdt_dialout_collector.dir/src/utils/cfg_handler.cc.o: In function `std::filesystem::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::filesystem::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::filesystem::__cxx11::path::format)':
cfg_handler.cc:(.text._ZNSt10filesystem7__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC5INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES1_EERKT_NS1_6formatE]+0x64): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/mdt_dialout_collector.dir/build.make:557: ../bin/mdt_dialout_collector] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/mdt_dialout_collector.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
[root@localhost build]#

**Comment by scuzzilla** [comment]
The whole install process is 100% correct, you just need to upgrade a newer gcc version.

--- Procedure ---
1. install a newer version of gcc - I tested it on CentOS with "gcc-toolset-11-11.0-1.el8.x86_64"
2. switch to the newer gcc (for example): scl enable gcc-toolset-11 bash
3. move to the app root & remove the build folder: cd mdt-dialout-collector; rm -rf build
4. restart the compile procedure from scratch: cd build; cmake ../; make

**Comment by Kevin-Patel119** [comment]
Thanks a lot @scuzzilla for detailed steps.

- Installed gcc-toolset-11 
[root@localhost build]# scl enable gcc-toolset-11 bash
[root@localhost build]# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/gcc-toolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/gcc-toolset-11/root/usr --mandir=/opt/rh/gcc-toolset-11/root/usr/share/man --infodir=/opt/rh/gcc-toolset-11/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-11.2.1-20220127/obj-x86_64-redhat-linux/isl-install --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC) 

- [root@localhost mdt-dialout-collector]# rm -rf build/
[root@localhost mdt-dialout-collector]# mkdir build
[root@localhost mdt-dialout-collector]# pushd build
/opt/mdt-dialout-collector/build /opt/mdt-dialout-collector
[root@localhost build]# cmake ../
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.4.2") 
-- The C compiler identification is GNU 11.2.1
-- The CXX compiler identification is GNU 11.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/gcc-toolset-11/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/gcc-toolset-11/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Protobuf: /root/.local/bin/protoc-3.19.4.0 (found version "3.19.4.0") 
-- Using protobuf 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using gRPC 1.46.3
-- Checking for module 'jsoncpp>=1.8.4'
--   Found jsoncpp, version 1.8.4
-- Using jsoncpp 1.8.4
-- Checking for module 'rdkafka++>=1.6.2'
--   Found rdkafka++, version 1.9.2
-- Using librdkafka++ 1.9.2
-- Checking for module 'rdkafka>=1.6.2'
--   Found rdkafka, version 1.9.2
-- Using librdkafka 1.9.2
-- Checking for module 'libconfig++>=1.5'
--   Found libconfig++, version 1.5
-- Using libconfig++ 1.5
-- Checking for module 'spdlog>=1.5.0'
--   Found spdlog, version 1.5.0
-- Using spdlog 1.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/mdt-dialout-collector/build

- [root@localhost build]# make
[  3%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/mdt_dialout_collector.cc.o
[  7%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/core/mdt_dialout_core.cc.o
[ 10%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/utils/cfg_handler.cc.o
[ 14%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/utils/logs_handler.cc.o
[ 17%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/dataManipulation/data_manipulation.cc.o
[ 21%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/dataDelivery/data_delivery.cc.o
[ 25%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Cisco/cisco_dialout.pb.cc.o
[ 28%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Cisco/cisco_dialout.grpc.pb.cc.o
[ 32%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Cisco/cisco_telemetry.pb.cc.o
[ 35%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_gnmi.pb.cc.o
[ 39%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_gnmi_ext.pb.cc.o
[ 42%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_dialout.pb.cc.o
[ 46%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_dialout.grpc.pb.cc.o
[ 50%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_telemetry.pb.cc.o
[ 53%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_telemetry_header.pb.cc.o
[ 57%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Juniper/juniper_telemetry_header_extension.pb.cc.o
[ 60%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Huawei/huawei_dialout.pb.cc.o
[ 64%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Huawei/huawei_dialout.grpc.pb.cc.o
[ 67%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/Huawei/huawei_telemetry.pb.cc.o
[ 71%] Building CXX object CMakeFiles/mdt_dialout_collector.dir/src/proto/OpenConfig/openconfig_interfaces.pb.cc.o
[ 75%] Linking CXX executable ../bin/mdt_dialout_collector
[100%] Built target mdt_dialout_collector

@scuzzilla I do see an error while running below commands,
- [root@localhost build]# ../bin/mdt_dialout_collector
[2022-09-14 05:56:58.128] [multi-logger-boot] [debug] constructor: LogsCfgHandler()
[2022-09-14 05:56:58.128] [multi-logger-boot] [error] configuration file issues: FileIOException
[root@localhost build]# date
Wed Sep 14 05:57:13 UTC 2022

**Comment by scuzzilla** [comment]
you have two options:
1. specify a config file from the command line. 
2. create a configuration file within the default location as mentioned in the README.

**Comment by Kevin-Patel119** [comment]
Thanks @scuzzilla 2nd option worked for us.

Is the MDT collector is multi threaded? Can it have multiple connections to port 10007 or do we need to run a collector instance for every telemetry connection when we have multiple routers and therefore multiple connections.

**Comment by scuzzilla** [comment]
Multi threaded and each thread is using async API

**Comment by Kevin-Patel119** [comment]
Thanks a lot @scuzzilla for your prompt response. 
I really appreciated.
