### ISSUE TITLE
Docs: centos_INSTALL.md and debian_INSTALL.md, paths

### ISSUE THREAD

**Issue by paololucente** [scuzzilla/mdt-dialout-collector#16]
I recommend replacing the instances of `/root` with `$HOME`.

Also i wonder if `cd /opt` are real necessary or can be changed to `cd /tmp`.

**Comment by scuzzilla** [comment]
Hi @paololucente ,

(it's clearly not the final *_INSTALL version).

At the moment, to make it simpler, I'm assuming that the whole procedure is conducted as 'root'.

for what concerning '/opt' it is probably a good choice whenever the standalone version of the collector is installed, however it's not really necessary when the library version is installed.

**Comment by scuzzilla** [comment]
Hi @paololucente ,

the *_INSTALL procedures are now officially deprecated. [install.sh](https://github.com/scuzzilla/mdt-dialout-collector/blob/main/install.sh) should be used instead.
