### ISSUE TITLE
Code: recommend to rename struct Payload to avoid namespace conflicts

### ISSUE THREAD

**Issue by paololucente** [scuzzilla/mdt-dialout-collector#18]
In `src/bridge/grpc_collector_bridge.h` it is defined `struct Payload`. Such naming is very generic and, when used in 3rd party tools (ie. pmacct), it may be source of namespace conflicts. I would recommend to rename it to something more specific, ie. `grpcPayload` or something like that.

```
    typedef struct {
        char *event_type;
        char *serialization;
        char *writer_id;
        char *telemetry_node;
        char *telemetry_port;
        char *telemetry_data;
    } __attribute__ ((packed)) Payload;
```

**Comment by scuzzilla** [comment]
renaming  done.
